USE								[7ELE]
GO
IF EXISTS						(SELECT * FROM sys.procedures WHERE [name] = 'usp_Move_STG_To_PROD')
BEGIN
DROP PROCEDURE					[dbo].[usp_Move_STG_To_PROD]
END
GO
CREATE PROCEDURE				[dbo].[usp_Move_STG_To_PROD]
AS
SET NOCOUNT ON
TRUNCATE TABLE					[dbo].[stg_122_Details]
TRUNCATE TABLE					[dbo].[stg_121_Headers]
INSERT INTO						[dbo].[prod_121_Headers]
(
								[RecordId],
								[StoreNumber],
								[TransactionType],
								[DayNumber],
								[ShiftNumber],
								[TransactionUID],
								[Aborted],
								[DeviceNumber],
								[DeviceType],
								[EmployeeNumber],
								[EndDate],
								[EndTime],
								[StartDate],
								[StartTime],
								[Status],
								[TotalAmount],
								[TransactionCode],
								[TransactionSequence],
								[RewardMemberID],
								[StageInsertStamp],
								[CsvFile],
								[DataLakeFolder],
								[Pk]
)
SELECT
								[RecordId],
								[StoreNumber],
								[TransactionType],
								[DayNumber],
								[ShiftNumber],
								[TransactionUID],
								[Aborted],
								[DeviceNumber],
								[DeviceType],
								[EmployeeNumber],
								[EndDate],
								[EndTime],
								[StartDate],
								[StartTime],
								[Status],
								[TotalAmount],
								[TransactionCode],
								[TransactionSequence],
								[RewardMemberID],
								[StageInsertStamp],
								[CsvFile],
								[DataLakeFolder],
								[Pk]
FROM							[dbo].[stg_121_Headers]

INSERT INTO						[dbo].[prod_122_Details]
(
								[RecordID],
								[StoreNumber],
								[TransactionType],
								[DayNumber],
								[ShiftNumber],
								[TransactionUID],
								[SequenceNumber],
								[ProductNumber],
								[PLUNumber],
								[RecordAmount],
								[RecordCount],
								[RecordType],
								[SizeIndx],
								[ErrorCorrectionFlag],
								[PriceOverideFlag],
								[TaxableFlag],
								[VoidFlag],
								[RecommendedFlag],
								[PriceMultiple],
								[CarryStatus],
								[TaxOverideFlag],
								[PromotionCount],
								[SalesPrice],
								[MUBasePrice],
								[HostItemId],
								[CouponCount],
								[StageInsertStamp],
								[CsvFile],
								[DataLakeFolder],
								[Pk]
)
SELECT
								[RecordID],
								[StoreNumber],
								[TransactionType],
								[DayNumber],
								[ShiftNumber],
								[TransactionUID],
								[SequenceNumber],
								[ProductNumber],
								[PLUNumber],
								[RecordAmount],
								[RecordCount],
								[RecordType],
								[SizeIndx],
								[ErrorCorrectionFlag],
								[PriceOverideFlag],
								[TaxableFlag],
								[VoidFlag],
								[RecommendedFlag],
								[PriceMultiple],
								[CarryStatus],
								[TaxOverideFlag],
								[PromotionCount],
								[SalesPrice],
								[MUBasePrice],
								[HostItemId],
								[CouponCount],
								[StageInsertStamp],
								[CsvFile],
								[DataLakeFolder],
								[Pk]
FROM							[dbo].[stg_122_Details]
